import './globals.css'
import type { Metadata } from 'next'
import { GeistSans, GeistMono } from 'geist/font'
import Navbar from './_components/Navbar'
import { Providers } from './provider'
import Footer from './_components/Footer'
import { Poppins } from"next/font/google"

const poppins = Poppins({
  weight:"400",
  display: 'swap',
  subsets: ['latin', 'devanagari', 'latin-ext'],

})
export const metadata: Metadata = {
  title: 'Prithviraj Tiwari | Top T',
  description: 'Generated by my unmatched Intellect',
  other:{
    'google-site-verification':"rxjXUQfb2q0XB-9D6w9YKSkm1m4JUHqDs6l8tgXCPuQ"
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark:bg-[#040d35] light:bg-[#afbbf4] text-foreground" >
      <body className={poppins.className}>

        <Providers>
          <Navbar />
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
